// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXY881L4SjFdm4grZ5x0vuRXMw5c_04U',
    appId: '1:1077301912159:web:430ecfc4a81547a80a71ea',
    messagingSenderId: '1077301912159',
    projectId: 'techwareproducts',
    authDomain: 'techwareproducts.firebaseapp.com',
    storageBucket: 'techwareproducts.firebasestorage.app',
    measurementId: 'G-JMDVNCPZR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPm_L_WJuRQGn11FFWGspNytW8SWDUdvc',
    appId: '1:1077301912159:android:125f5b521a5d21f60a71ea',
    messagingSenderId: '1077301912159',
    projectId: 'techwareproducts',
    storageBucket: 'techwareproducts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FJCxgl9ETEKn586wVogLniYRS7UeF_I',
    appId: '1:1077301912159:ios:80c679cea825cf350a71ea',
    messagingSenderId: '1077301912159',
    projectId: 'techwareproducts',
    storageBucket: 'techwareproducts.firebasestorage.app',
    iosBundleId: 'com.example.techwareProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FJCxgl9ETEKn586wVogLniYRS7UeF_I',
    appId: '1:1077301912159:ios:80c679cea825cf350a71ea',
    messagingSenderId: '1077301912159',
    projectId: 'techwareproducts',
    storageBucket: 'techwareproducts.firebasestorage.app',
    iosBundleId: 'com.example.techwareProducts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXY881L4SjFdm4grZ5x0vuRXMw5c_04U',
    appId: '1:1077301912159:web:60a28cfe0388f7a70a71ea',
    messagingSenderId: '1077301912159',
    projectId: 'techwareproducts',
    authDomain: 'techwareproducts.firebaseapp.com',
    storageBucket: 'techwareproducts.firebasestorage.app',
    measurementId: 'G-NJDW40Y8Y6',
  );
}
